name: Build and Deploy
on:
  push:
    branches:
      - master

jobs:
  build:
    name: Build & Deploy
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Install Dependencies
        run: npm install
      - name: Build
        run: npm run build:firebase
      - name: Change Directory
        run: cd functions
      - name: Install Dependencies (Functions)
        run: npm install
      - name: Install Firebase Tools
        run: npm install -g firebase-tools
      - name: Deploy to Firebase
        run: firebase deploy
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_SERVICE_ACCOUNT_POKEMON_APP_51156 }}
