name: Deployment
on:
  push:
    branches: [ master ]

jobs:  
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Install Dependencies
        run: npm install
      - name: Build App
        run: npm run build:firebase
  
  deploy-function:
    name: Deploy Function
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@master
    - name: Install npm packages (functions)
      run: |
        cd functions
        npm install
    - name: Deploy to Firebase Functions
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  
  deploy-hosting:
    name: Deploy Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
