name: Deployment
on:
  push:
    branches: [ master ]

jobs:  
  deploy-function:
    name: Deploy Function
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@master
    - name: Build
      run: npm run build:firebase
    - name: Install npm packages (functions)
      run: |
        cd functions
        npm install
    - name: Deploy to Firebase Functions
      uses: w9jds/firebase-action@master
      with:
          args: deploy --only functions
      env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
  
  deploy-hosting:
    name: Deploy Hosting
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Repo
        uses: actions/checkout@master
      - name: Build 
      - run: npm run build:ssr
      - name: Deploy to Firebase Hosting
        uses: w9jds/firebase-action@master
        with:
          args: deploy --only hosting
        env:
          FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
